Gemfile.lock
app/models/where_did_you_hear.rb
db/migrate/20160428162511_create_where_did_you_hears.rb
db/schema.rb
lib/importers.rb
lib/importers/where_did_you_hear_about_us.rb
lib/importers/where_did_you_hear_about_us/google.rb
lib/importers/where_did_you_hear_about_us/google/importer.rb
lib/tasks/import.rake
spec/features/import_google_where_did_you_hear_data_spec.rb

Imports the google forms backed 'where did you hear' data. This is a
one-off task that can be scrapped after the cut-off period for our usage of
google forms for the 'where did you hear' data.
At the moment we just take the data as-is. Some of this appears to be of
'varying' quality. I'm sure we'll need some manual cleanup once complete.
Imports from the provided `CSV` and `PARTNER` environment variables. For
example:
```
$ bundle exec rake import:google CSV=file.csv PARTNER=CAS
```

Add simple import for google-based data

---

Gemfile.lock

We are somehow using a super-dated version of puma. We're so far behind
and there have been many critical bugs fixed in that time so I'm
bumping us up here.

Bump `puma`

---

.travis.yml
Gemfile
Gemfile.lock
app/controllers/reports_controller.rb
app/forms/where_did_you_hears.rb
app/services/where_did_you_hear_csv.rb
app/views/layouts/application.html.erb
app/views/reports/where_did_you_hear.html.erb
config/routes.rb
db/seeds.rb
features/pages/where_did_you_hear_about_us_report_page.rb
features/step_definitions/where_did_you_hear_about_us_report_steps.rb
features/support/factory_girl.rb
features/where_did_hear_about_us_report.feature
spec/factories.rb
spec/forms/where_did_you_hears_spec.rb
spec/services/where_did_you_hear_csv_spec.rb
spec/support/factory_girl.rb

Adds a simple dashboard for querying these particular records. At the moment
this is by date range only, but could reasonably be extended to cover the
delivery partners or other criteria.
The duplication in the forms and CSV generators could do with some form of
abstraction soon, if we keep repeating them.

Add 'where did you hear about us?' dashboard

---

app/services/csv_generator.rb
app/services/daily_call_volume_csv.rb
app/services/where_did_you_hear_csv.rb

Moves the common CSV generation behaviour into a newly abstracted
`CsvGenerator`. You can control formatting of specific attributes by
overriding `attribute_formatter` where `attribute` is the name of the
attribute that needs custom formatting.

Abstract CSV generation

---

app/models/where_did_you_hear.rb
app/services/where_did_you_hear_csv.rb
app/views/reports/where_did_you_hear.html.erb
db/migrate/20160512135735_rename_dumb_attributes.rb
db/schema.rb
lib/importers/tp/call_record.rb
spec/factories.rb
spec/features/import_tp_call_data_spec.rb
spec/services/where_did_you_hear_csv_spec.rb

Naming a column `where`, on reflection, was not the greatest idea. It
seems to have uncovered an issue with quoted naming for reserved words
in Rails. Rather than attempting to resolve this I've decided just to
take the easy route for now and rename the attribute(s).

Renamed `where*` columns

---

config/initializers/importers.rb
lib/importers/tp/call_record.rb
lib/importers/tp/importer.rb
lib/importers/tp/retriever.rb
spec/features/import_tp_call_data_spec.rb

This is required to import the initial monthly
email which has a different subject, filename and
sheet name compared to the daily emails.

Make the TP importer more configurable

---

config/initializers/date_formats.rb
spec/forms/where_did_you_hears_spec.rb

Prior to this change, `#to_s` on date-like objects would include the
time portion, thus causing warnings and unexpected results when
attempting to bind the value to an HTML5 date picker. This change
ensures we strip the time portion when presenting a `DateTime`.
Traditionally, I'd prefer an integration spec that proves this
behaviour, but capybara has problems with HTML5 date pickers so that
proved fruitless.

Ensure HTML5 date pickers can be bound

---

app/services/where_did_you_hear_summary.rb
spec/services/where_did_you_hear_summary_spec.rb

* Order results by `count` descending
* Display 'N / A' for blank 'heard from' entries
I tested the ordering in memory with a set of 10,000 records and the overheard
is negligible.

WDYH Summary Tweaks

---

spec/services/where_did_you_hear_summary_spec.rb

`match_array` doesn't respect ordering, dummy.

Ensure ordering is asserted upon

---

db/migrate/20160519134429_add_raw_field_to_wdyh.rb
db/schema.rb
db/seeds/code_lookups.rb
lib/importers/tp/call_record.rb

Issue with UID creation resulted in duplicate
entries being created, however we could not 
isolate why. storing this data will allow further
investigation if this happen again.

Store raw UID data on WDYH record

---

lib/importers/smart_survey/call_record.rb

This requires the underlying WDYH data to be updated 
as follows:
```
WhereDidYouHear
.where(heard_from_raw: 'Newspaper/Magazine advert')
.update_all(heard_from_code: 'WDYH_NEWS', heard_from: 'Advertising')
```

Add WDYH mapping for newspapers/magazine adverts

---

app/models/appointment.rb
db/migrate/20160610105240_create_appointments.rb
db/migrate/20160610105323_create_appointment_versions.rb
db/schema.rb
lib/importers/booking_bug/record.rb
lib/importers/booking_bug/saver.rb
lib/importers/booking_bug/summary_saver.rb
spec/factories.rb
spec/features/import_booking_bug_data_spec.rb

Cancelled at date should be used when counting transaction (if the booking is cancelled)
Reporting for the month should be for events during the month not for all time.

Add transaction at to handle cancelled timings and fix summary window

---

.rubocop.yml

Make the following line valid:
```
if apples = find_fruit(:red)
apples.grow
end
```
Where previously it would have required the assignment
to be wrapped in brackets.

Rubocop: allow assignment in condition without brackets

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_form-group.scss
app/assets/stylesheets/lib/_variables.scss
app/controllers/appointment_summaries_controller.rb
app/forms/appointment_summaries.rb
app/models/appointment_summary.rb
app/views/appointment_summaries/_error.html.erb
app/views/appointment_summaries/_form.html.erb
app/views/appointment_summaries/edit.html.erb
app/views/appointment_summaries/index.html.erb
app/views/appointment_summaries/new.html.erb
app/views/appointment_summaries/show.html.erb
app/views/layouts/application.html.erb
config/initializers/show_flash.rb
config/locales/en.yml
config/routes.rb
db/migrate/20160616130135_populate_historical_appointment_summary_data.rb
db/schema.rb
features/manual_appointment_summary_data.feature
features/pages/edit_appointment_summary_page.rb
features/pages/new_appointment_summary_page.rb
features/step_definitions/appointment_summary_steps.rb
features/step_definitions/call_volumes_report_steps.rb
features/step_definitions/login_steps.rb
spec/factories.rb

Allow manual creation/and deletion of appointment summary data.
`/appointment_summaries` shows appointment figures by month for the filtered delivery partner
`/appointment_summaries/<reporting_month>` shows appointment for the selected month by delivery partner

Manual entry appointment summary data

---

spec/features/import_booking_bug_data_spec.rb

Fixture data is for the specific date so fails unless 
test is locked.

Lock test to fixture month

---

lib/importers/booking_bug/importer.rb
lib/importers/booking_bug/record.rb
spec/features/import_booking_bug_data_spec.rb

These are caused by blocking out the guiders diary
__NOTE:__
This will require a purge and reimport of all TPAS appointment data

Exclude Booking bug appointments with invalid service name

---

lib/importers/booking_bug/retriever.rb
spec/cassettes/booking_bug_data.yml

Changing to Booking status doesn't appear to update 
the last modified time on the record. Given max lead 
time to an appointment of 6 week, 90 days (approx 12 weeks)
should mean we capture all updates without having to 
import the full dataset each day.

Extend BookingBug data import window

---

app/models/twilio_call.rb
config/initializers/importers.rb
db/migrate/20160817132701_create_twilio_calls.rb
db/schema.rb
lib/importers/twilio.rb
lib/importers/twilio/call_record.rb
lib/importers/twilio/importer.rb
lib/importers/twilio/saver.rb
lib/importers/twilio/twilio_lookup.rb
lib/location_api.rb
spec/features/import_twilio_call_data_spec.rb
spec/lib/importers/twilio/call_record_spec.rb
spec/lib/importers/twilio/saver_spec.rb
spec/models/twilio_call_spec.rb

In order to facilitate the PMB report we need to
additionally store the delivery partner, location 
and booking location for each call.
Postcode for location and booking location as also
stored to allow manual mapping to region as required.
Abandoned (calls < 10sec) and failed (inbound calls 
without a corresponding outbound call) are also being 
logged.

Store Twilio call records

---

db/migrate/20160822104923_increase_cost_scale.rb
db/schema.rb
lib/importers/twilio/call_record.rb
spec/lib/importers/twilio/call_record_spec.rb
spec/models/twilio_call_spec.rb

Increase scale on twilio cost DB field to ensure that we can accurately store the data retrieved from twilio.
Handle an edge case related to calls that exist with a duration of 0 being given a price of nil.

Twilio cost edge cases

---

app/controllers/reports_controller.rb
app/forms/call_volumes.rb
app/models/twilio_call.rb
app/services/daily_call_volume_csv.rb
app/services/twilio_calls_csv.rb
app/view_models/call_volume.rb
app/views/layouts/application.html.erb
app/views/reports/call_volumes.html.erb
config/routes.rb
features/call_volumes_report.feature
features/pages/call_volumes_report_page.rb
features/step_definitions/call_volumes_report_steps.rb
spec/factories.rb
spec/services/daily_call_volume_csv_spec.rb
spec/services/twilio_calls_csv_spec.rb

Allow twilio data to be reported at a PMB report 
level (DP breakdown)
- Add breakdown by DP to report view and export.
- Add export of raw calls with all stored data fields

Display and export breakdown of Twilio calls

---

app/services/csv_generator.rb
app/services/daily_call_volume_csv.rb
app/services/satisfaction_csv.rb
app/services/satisfaction_summary_csv.rb
app/services/twilio_calls_csv.rb
app/services/where_did_you_hear_csv.rb
config/initializers/csv_renderer.rb
lib/importers/google/satisfaction/call_record.rb
spec/services/daily_call_volume_csv_spec.rb
spec/services/twilio_calls_csv_spec.rb

This was added to satisfy a rubocop rule which has since been disabled.
The comment has been removed from files where it does not affect the code.
i.e. no unfrozen string literals exist.

Remove `frozen_string_literal` from files

---

app/controllers/reports_controller.rb
app/forms/call_volumes.rb
app/models/tp_call.rb
app/services/tp_calls_csv.rb
app/views/reports/call_volumes.html.erb
config/routes.rb
db/migrate/20161013122933_create_tp_calls.rb
db/schema.rb
lib/importers/tp/call_record.rb
lib/importers/tp/saver.rb
spec/features/import_tp_data_spec.rb

Store outcome data for TP calls.
This has been stored in a new table meaning we now have three tables for 
call data:
* DailyCAllVolume
* TwilioCall
* TpCall
while this is not ideal it does give us the functionality we want as the two datasets (TP/Twilio) have very little overlap in data and functionality.

Tp call outcomes

---

app/services/satisfaction_summary.rb
features/step_definitions/satisfaction_report_steps.rb

Bug created by store web sessions in appointment
summary table (transactions). This makes sense for
the costing report but broke the satisfaction report.
This fix pre filters the appointment summary data
to the valid set before applying completion numbers.

Fix satisfaction report bug

---

app/services/twilio_calls_csv.rb
db/migrate/20161019151220_add_hours_to_twilio_calls.rb
db/schema.rb
lib/importers/twilio/call_record.rb
lib/importers/twilio/twilio_lookup.rb
lib/tasks/data_migration.rake
spec/factories.rb
spec/jobs/import_twilio_data_job_spec.rb
spec/services/twilio_calls_csv_spec.rb

This is stored on the object so that changes
over time can be ignored, as the object will have
the opening hours from the date it was imported
(move forward).
__This change was requested from the Analytics team.__

Store opening hours on Twilio Call

---

lib/importers/tp/call_record.rb
spec/lib/importers/tp/call_record_spec.rb

This makes the importer more resilient to changes
as previously incorrectly adding a column would
break this importer.
Since 17 Oct some data has imported correctly and some has not. 
The issue appears to be caused by the UID column not being consistent.
Once this change is in all data since the 17th will be re-imported.

Use column names instead of indices

---

app/services/twilio_calls_csv.rb
db/migrate/20161102150908_add_outbound_call_outcome_to_twilio_calls.rb
db/schema.rb
lib/importers/twilio/call_record.rb
spec/factories.rb
spec/features/import_twilio_call_data_spec.rb
spec/services/twilio_calls_csv_spec.rb

This will give more visibility to busy and unanswered
calls to CAB offices.
This fields can have the following values:
* <blank> - no call was made
* completed - the call was ended normally
* busy - line was busy
* no-answer - no one answered
* failed - the number was invalid

Add outbound call outcome to twilio calls

---

lib/importers/twilio/call_record.rb
lib/importers/twilio/saver.rb
spec/features/import_twilio_call_data_spec.rb

This is required to allow population of new data fields
without deleting historical data. This is important
as location based data is a snap shot of the point
in time that it was imported.

Update static data on TwilioCall during reimport

---

app/view_models/cost_per_transaction.rb
app/view_models/cost_per_transaction/cost_by_delivery_partner.rb
app/view_models/cost_per_transaction/split_by_call_volume.rb
spec/view_models/cost_per_transaction/split_by_call_volume_spec.rb

This bug presents when entering data for May 2015 as
twilio was only used from Aug 2015 onwards.
This fix uses calls volumes from the next month with any
calls if no calls exists for the given month.
An additionally fallback has been added in case future cost
data is entered. In this case it will split based on
call volumes from the previous month with call data.

Fix bug with costs breakdown report when no twilio calls

---

app/models/cost_item.rb
app/view_models/costs/item.rb
app/view_models/costs/month_item.rb
spec/view_models/costs/item_spec.rb
spec/view_models/costs/month_item_spec.rb

It makes more sense to eager load the data and then
partition in code that make an extra database call
for each cost_item/month combination.

Refactor the cost reporting to reduce DB calls

---

app/forms/where_did_you_hears.rb
app/services/cost_breakdown_raw_csv.rb
config/initializers/date_formats.rb
lib/importers/tp/call_record.rb
lib/twilio_numbers/phone_numbers.rb
spec/forms/where_did_you_hears_spec.rb

This was a bad idea from the start and now causes problems with
exporting CSV data using blazer. Where we need to format timestamps
without the time portion we now do this explicitly.

Don't default time formatting

---

config/blazer.yml

When we report on historical data we need to display location names
regardless whether they've been since hidden.

Include hidden locations in smart columns

---

db/seeds/code_lookups.rb

Adds new mappings since the standard WDYH entries have also changed.
They are no longer represented by 'code' so we can just map directly
from one to the other. For older codes this still just works. Hence the
apparent duplication.

Add new WDYH mappings for TP

---

app/models/code_lookup.rb
db/seeds/code_lookups.rb
lib/importers/smart_survey/call_record.rb
spec/features/import_smart_servey_data_spec.rb

Ensures the simplified mappings are used. This includes deprecating the
`pension_provider` field in this context as it is no longer used.

Handle new mappings

---

db/seeds/code_lookups.rb

This is to accommodate the new entries during surveys and the customer
journeys.

Map 'Jobcentre Plus' for reporting

---

lib/importers/google/satisfaction/call_record.rb
spec/cassettes/google_satisfaction_data.yml
spec/features/import_google_satisfaction_data_spec.rb

The exit polls have changed for face-to-face appointments and we need
to alter the way we process and import the google satisfaction data to
match the new shape and structure of this data.
The headline changes are:
* Keyword changes for the raw satisfaction value
* Simplified locations, raw satisfaction (unified positionally)
* Accurate appointment dates
Appointment times are fudged to `09:00` since the time portion of the
appointment is not accurately reported. Previously we were incorrectly
using the date/time from the `timestamp`. This represents the date/time
the data was entered, not the actual appointment date/time.

Accommodate new exit poll for reporting

---

config/initializers/importers.rb
lib/importers/smart_survey/retriever.rb
lib/mail_retriever.rb
spec/features/import_smart_survey_data_spec.rb

Smart Survey do not include the plain-text part in export emails so we
must instead parse the HTML part.

Parse Smart Survey email HTML part

---

db/migrate/20180716134914_add_missing_indexes.rb
db/schema.rb

The lack of indexes on these fields absolutely tanks the reads that
occur in very high numbers during the various batch import routines.

Add key missing indexes

---

lib/importers/tp_satisfaction/importer.rb
lib/importers/tp_satisfaction/record.rb

Try and access the first sheet more reliably since TP sometimes change
the sheet name. Accessing by ordinal should be safer since there is only
ever one sheet provided.
We log the found sheet names just for instrumentation purposes.

Improve sheet access

---

lib/importers/tp/call_record.rb
lib/importers/tp/importer.rb

This means we no longer rely on TP naming to stay consistent.

Access sheets ordinally

---

lib/mail_retriever.rb
spec/lib/mail_retriver_spec.rb

This default has changed due to the migration away from google.

Configure the office 365 IMAP server

---

lib/importers/cita_satisfaction/record.rb

Some of the emails are mixed case and the 'Exit Poll' part is discarded
anyway so there is no need to be so specific.

Parse the subject case-insensitive
