app/controllers/reports_controller.rb, app/forms/call_volumes.rb, app/services/daily_call_volume_csv.rb, app/views/reports/call_volumes.html.erb, config/initializers/csv_renderer.rb, features/call_volumes_report.feature, features/pages/call_volumes_report_page.rb, features/step_definitions/call_volumes_report_steps.rb, spec/services/daily_call_volume_csv_spec.rb
This is taken from the work by @benlovell for application summary exporting
=> Export call volumes to CSV

config/database.yml
Corrects a typo in the environment key and configures the pool size.
=> Configure production database

Gemfile, Gemfile.lock, app/controllers/reports_controller.rb, app/services/where_did_you_hear_summary.rb, app/views/reports/_where_did_you_hear_filters.html.erb, app/views/reports/where_did_you_hear.html.erb, app/views/reports/where_did_you_hear_summary.html.erb, config/routes.rb, features/pages/where_did_you_hear_about_us_report_page.rb, features/step_definitions/where_did_you_hear_about_us_report_steps.rb, features/where_did_hear_about_us_report.feature, spec/services/where_did_you_hear_summary_spec.rb
Adds a simple report to summarise the totals for 'where did you hear' data.
=> Summarise 'where did you hear' records

lib/importers/tp/call_record.rb, lib/importers/tp/saver.rb
Do not record WDYH results for specific call
outcomes.
=> WDYH call outcome filtering

app/controllers/reports_controller.rb, app/forms/call_volumes.rb, app/forms/satisfactions.rb, app/models/delivery_partner.rb, app/services/satisfaction_csv.rb, app/services/satisfaction_summary.rb, app/services/satisfaction_summary/average_column.rb, app/services/satisfaction_summary/formatter.rb, app/services/satisfaction_summary/partner_column.rb, app/services/satisfaction_summary/row.rb, app/services/satisfaction_summary/total_column.rb, app/services/satisfaction_summary_csv.rb, app/views/layouts/application.html.erb, app/views/reports/satisfaction_summary.html.erb, config/routes.rb, features/call_volumes_report.feature, features/pages/satisfaction_report_page.rb, features/satisfaction_report.feature, features/step_definitions/call_volumes_report_steps.rb, features/step_definitions/satisfaction_report_steps.rb, features/step_definitions/where_did_you_hear_about_us_report_steps.rb
Report for summarised satisfaction data. This report is a work in progress as
it still requires numbers for TPAS satisfaction and for Appointments completed 
for each delivery partner.
=> Satisfaction report

lib/importers/tp/saver.rb, spec/features/import_tp_data_spec.rb
Daily calls should not include 'TEST CODE' outcomes
=> Add outcome filtering for daily calls to TP importer

config/initializers/importers.rb, lib/importers/booking_bug/record.rb, spec/lib/importers/booking_bug/record_spec.rb
Correct process when booking bug status = "" 
Currrently this raises an error as it does not assign the default status to the record
=> Booking bug status bug

app/controllers/reports_controller.rb, app/forms/satisfactions.rb, app/services/satisfaction_summary.rb, app/services/satisfaction_summary/partner_column.rb, app/views/reports/satisfaction_summary.html.erb, features/pages/satisfaction_report_page.rb, features/satisfaction_report.feature, features/step_definitions/satisfaction_report_steps.rb
Change report period to calendar month inline with completion data and analyst requirements.
Add completion data to satisfaction rpoert.
=> Satisfaction period set to month

.rubocop.yml, app/assets/javascripts/check-for-edits-before-submit.js, app/assets/javascripts/summable-values.js, app/assets/stylesheets/layouts/_costs.scss, app/controllers/reports_controller.rb, app/forms/costs_report.rb, app/models/cost.rb, app/models/cost_item.rb, app/view_models/cost_per_transaction.rb, app/view_models/cost_per_transaction/cost_by_delivery_partner.rb, app/view_models/cost_per_transaction/split_by_call_volume.rb, app/view_models/cost_per_transaction/values.rb, app/view_models/costs/items.rb, app/views/cost_items/index.html.erb, app/views/costs/index.html.erb, app/views/layouts/application.html.erb, app/views/reports/_cost_per.html.erb, app/views/reports/costs.html.erb, config/routes.rb, db/seeds/cost_items.rb, features/pages/cost_report_page.rb, spec/factories.rb, spec/features/costs_reporting_spec.rb, spec/view_models/cost_per_transaction/cost_by_delivery_partner_spec.rb, spec/view_models/cost_per_transaction/split_by_call_volume_spec.rb
Create report for cost per transaction by month with a value for:
* Overall
* Web
* by Delivery partner
Delivery partner costs can either be:
* a direct map 
* split by call volume (ie Twilio)
=> Cost per transaction report

app/views/appointment_summaries/index.html.erb, app/views/appointment_summaries/show.html.erb, app/views/cita_appointment_uploads/new.html.erb, app/views/cost_items/edit.html.erb, app/views/cost_items/index.html.erb, app/views/cost_items/new.html.erb, app/views/reports/call_volumes.html.erb, app/views/reports/where_did_you_hear.html.erb
These should be in sentence case not title case
Get heads, links, etc to be consistent
=> Consistent capitalisation

app/controllers/reports_controller.rb, app/forms/costs_report.rb, app/helpers/application_helper.rb, app/models/appointment_summary.rb, app/services/cost_breakdown_csv.rb, app/services/cost_breakdown_raw_csv.rb, app/view_models/cost_per_transaction.rb, app/view_models/costs/item.rb, app/views/reports/costs.html.erb, config/routes.rb, features/pages/cost_report_page.rb, spec/factories.rb, spec/services/cost_breakdown_csv_spec.rb, spec/services/cost_breakdown_raw_csv_spec.rb
Export Cost per transaction as a CSV 
data can be exported in breakdown format -> grouped by cost item and month
and raw format -> individual deltas
=> Cost per transaction csv

app/services/tp_calls_csv.rb, db/migrate/20161025094246_add_location_to_tp_calls.rb, db/schema.rb, lib/importers/tp/call_record.rb, spec/features/import_tp_data_spec.rb
=> Add location to TP calls

app/controllers/reports_controller.rb, app/forms/twilio_numbers_report.rb, app/jobs/generate_twilio_numbers_report.rb, app/mailers/application_mailer.rb, app/mailers/twilio_numbers_report_mailer.rb, app/views/layouts/application.html.erb, app/views/reports/_error.html.erb, app/views/reports/twilio_numbers.html.erb, config/environments/production.rb, config/locales/en.yml, config/routes.rb, lib/twilio_numbers.rb, lib/twilio_numbers/location_details.rb, lib/twilio_numbers/phone_number.rb, lib/twilio_numbers/phone_numbers.rb, lib/twilio_numbers/recent_call_volumes.rb, lib/twilio_numbers/report.rb, lib/twilio_numbers/twilio_phone_numbers.rb, spec/cassettes/twilio_numbers_report.yml, spec/fixtures/twilio_numbers_report.csv, spec/forms/twilio_numbers_report_request_spec.rb, spec/lib/twilio_numbers/report_spec.rb, spec/rails_helper.rb
Report is generated on demand and then emailed to the requester.
A single report can be requested to multiple email address.
The report bring together the following data:
* Phone number owned in Twilio
* Call volumes
* Location details
=> Add phone number report

.rubocop.yml, Gemfile, Gemfile.lock, app/models/appointment_summary.rb, app/models/tp_call.rb, app/models/twilio_call.rb, lib/importers/google/satisfaction/call_record.rb, spec/features/import_booking_bug_data_spec.rb, spec/lib/twilio_numbers/report_spec.rb
This is in preparation for the rails 5 upgrade
=> Upgrade rubocop to latest version

app/forms/costs_report.rb, app/services/cost_breakdown_csv.rb, spec/services/cost_breakdown_csv_spec.rb
Update month to reporting_month.
This was missed in the previous data migration.
=> Fix costs reporting

app/jobs/import_tesco_satisfaction_data.rb, config/initializers/importers.rb, lib/importers.rb, lib/importers/tesco.rb, lib/importers/tesco/satisfaction.rb, lib/importers/tesco/satisfaction/call_record.rb, lib/importers/tesco/satisfaction/importer.rb, lib/importers/tesco/satisfaction/retriever.rb, lib/importers/tesco/satisfaction/saver.rb, lib/tasks/import.rake, spec/cassettes/tesco_satisfaction_data.yml, spec/features/import_tesco_satisfaction_data_spec.rb
Imports said data for internal reporting.
=> Import google satisfaction data for Tesco

app/services/satisfaction_summary.rb, app/services/satisfaction_summary/partner_column.rb, app/services/satisfaction_summary/total_column.rb
These rows were not modified to suit the new satisfaction ratings.
=> Alter satisfaction summary labels

config/blazer.yml
Allows us to report on Welsh language appointments.
=> Attach the Welsh language appointments follower

app/models/partners.rb, app/services/satisfaction_summary/row.rb, app/services/satisfaction_summary_csv.rb, app/views/reports/satisfaction_summary.html.erb, lib/importers/cas_satisfaction/record.rb
Separates the CAS satisfaction data by channel.
=> Separate CAS channels for summarisation

config/blazer.yml
Adds `status` for bookings and improves smart columns for locator
information.
=> Correct smart columns

app/jobs/import_cita_satisfaction_data.rb, app/models/partners.rb, app/services/satisfaction_summary/row.rb, app/services/satisfaction_summary_csv.rb, app/views/reports/satisfaction_summary.html.erb, config/initializers/importers.rb, lib/importers.rb, lib/importers/cita_satisfaction.rb, lib/importers/cita_satisfaction/importer.rb, lib/importers/cita_satisfaction/record.rb, lib/importers/cita_satisfaction/retriever.rb, lib/importers/cita_satisfaction/saver.rb, lib/tasks/import.rake, spec/features/import_cita_satisfaction_data_spec.rb, spec/fixtures/cita_satisfaction.csv
Imports the exported IVR data and summarises the numbers in the existing report.
=> Import CITA Wallsend satisfaction data

lib/importers/pwni_satisfaction/record.rb, spec/features/import_pwni_satisfaction_data_spec.rb
This ensures the UID is actually unique.
=> Build the UID from a digest of the cells

config/blazer.yml
Adds this to summary document queries.
=> Add smart columns for orgs

Gemfile, Gemfile.lock, lib/tasks/export.rake
Exports the satisfaction data to the azure blob storage for BI analysis
in that platform. This will be scheduled to run nightly.
=> Add export task for satisfaction data

Gemfile, Gemfile.lock
This switches to our branch with the added changes required to export smart values transposed into CSV exports for columns that match.
=> Switch to modified branch for CSV exports
